generatorName: cpp-qt-client
outputDir: samples/client/petstore/cpp-qt-unique-items
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore_plus_unique.json
templateDir: modules/openapi-generator/src/main/resources/cpp-qt-client
additionalProperties:
  cppNamespace: test_namespace
  modelNamePrefix: PFX
