generatorName: cpp-qt-client
outputDir: samples/client/petstore/cpp-qt-unqiue-items
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore_plus_unqiue.json
templateDir: modules/openapi-generator/src/main/resources/cpp-qt-client
additionalProperties:
  cppNamespace: test_namespace
  modelNamePrefix: PFX
